services:
  whr90-2-mqtt:
    image: ghcr.io/runtimeerror123/whr90-2-mqtt:latest
    restart: unless-stopped
    environment:
      # EW11 Modbus/TCP gateway
      EW11_IP: "192.168.1.50"         # mandatory
      EW11_PORT: "502"                # default: 502
      SOCKET_TIMEOUT: "2.0"           # default: 2.0
      POLL_INTERVAL_SEC: "5"          # default: 5

      # MQTT broker settings
      MQTT_BROKER: "mqtt.example.com" # default: localhost
      MQTT_PORT: "1883"               # default: 1883 / 8883 with TLS
      MQTT_KEEPALIVE: "60"            # default: 60
      MQTT_USERNAME: "user"           # optional
      MQTT_PASSWORD: "secret"         # optional
      MQTT_USE_TLS: "false"           # default: true
      CA_CERT: ""                     # optional
      CLIENT_CERT: ""                 # optional
      CLIENT_KEY: ""                  # optional
      MQTT_TLS_INSECURE: "false"      # default: false
      MQTT_TLS_VERSION: "TLSv1.2"     # optional

      # Metadata
      MQTT_PREFIX: "whr90"            # default: whr90
      NAME: "WHR90"                   # default: WHR90 Ventilation Unit
      MANUFACTURER: "J.E. Storkair"   # default: J.E. Storkair
